Fix capitalization of filenames in #include directives
Incorrect capitalization of the filenames caused compilation to fail on filename case-sensitive operating systems like Linux:

/home/builder/opt/libraries/latest/aistarter_1_0_1/src/SmartBot.h:21:21: fatal error: arduino.h: No such file or directory